version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

      # how do you know what to put for the volume?
    # volumes:
    # - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
